# Create a 3x3x3 array with random values


In [2]:
import numpy as np
from numpy import array
x=np.empty((3,3,3))
x

array([[[4.67296746e-307, 1.69121096e-306, 7.56602523e-307],
        [1.42418444e-306, 1.11260280e-306, 1.33511018e-306],
        [1.33511969e-306, 6.23037996e-307, 6.23053954e-307]],

       [[9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
        [1.86921143e-306, 6.23061763e-307, 8.90104239e-307],
        [6.89804132e-307, 1.24611266e-306, 8.45559303e-307]],

       [[8.06612616e-308, 6.89810244e-307, 1.22387550e-307],
        [2.22522596e-306, 8.34423917e-308, 1.11261162e-306],
        [1.78021527e-306, 2.12203497e-312, 2.46155235e-312]]])

In [8]:
y=np.random.random((3,3,3))
y

array([[[0.64628594, 0.64588734, 0.05190154],
        [0.92713246, 0.94665416, 0.67813862],
        [0.84482979, 0.96659445, 0.39320664]],

       [[0.1835034 , 0.4168262 , 0.79029771],
        [0.39108268, 0.50767564, 0.77348129],
        [0.39623124, 0.47561271, 0.87510817]],

       [[0.78026292, 0.35425373, 0.92213205],
        [0.36703837, 0.01045625, 0.75179184],
        [0.58809682, 0.41751551, 0.2503576 ]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
z=np.diag(1+np.arange(4),k=-1)   #.diag-->gives acess to the diagonalindices.
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# Create a 8x8 matrix and fill it with a checkerboard pattern

In [25]:
w = np.zeros((8,8))
w[1::2 , ::2]=1
w[0::2 , 1::2]=1
w

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# Normalize a 5x5 random matrix


In [35]:
U=np.random.random((5,5))
Umax,Umin =U.max(),U.min()
v=(U-Umin)/(Umax-Umin)       # (element in U - min value in U ) / (max in U-min in U)
v

array([[0.73630132, 0.62507219, 0.37148442, 1.        , 0.8083469 ],
       [0.38750061, 0.01344287, 0.89320015, 0.94330833, 0.43627759],
       [0.        , 0.20354418, 0.08060914, 0.46441838, 0.14815426],
       [0.2254073 , 0.40260532, 0.66974909, 0.083797  , 0.037186  ],
       [0.23283663, 0.83137678, 0.59425317, 0.71725608, 0.99089889]])

# 5. How to find common values between two arrays?

In [31]:
a=np.array([1,2,3,4,5,6])
b=np.array([2,4,6,8,9,7])
print(a)
print(b)
for x in a:
    for y in b:
        if (x == y ):
        
            print("common values between 2 arrays :",(x&y))


[1 2 3 4 5 6]
[2 4 6 8 9 7]
common values between 2 arrays : 2
common values between 2 arrays : 4
common values between 2 arrays : 6


In [33]:
a=np.array([1,2,3,4,5,6])
b=np.array([2,4,6,8,9,7])
print("common values: ",np.intersect1d(a,b))  # intersect1d is a function for finding common betwen 2 arrays.

common values:  [2 4 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [38]:
yesterday= np.datetime64('today','D')-np.timedelta64(1,'D')   #datetime64  and timedelta64 are 2 funct to get the dates
today =np.datetime64('today','D')
tomorrow = np.datetime64('today','D')+np.timedelta64(1,'D')
print('Yesterday',yesterday)
print('Today',today)
print('Tomorrow',tomorrow)

Yesterday 2020-07-28
Today 2020-07-29
Tomorrow 2020-07-30


# 7. Consider two random array A and B, check if they are equal

In [44]:
a1=np.array([1,2,3,4])
a2=np.array([2,3,4,5])
c=np.allclose(a1,a2)
print("they are equal(TRUE|False): ",c)

they are equal(TRUE|False):  False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [60]:
v1 =np.random.random(10)
print(v1)
v1max=v1.max()
print("max value is : ",v1max)    
v1[v1.argmax()]=0                #argmax() is the function to find max value .
print(v1)

[0.45190414 0.08437286 0.5112379  0.71570032 0.66687816 0.73578877
 0.76348427 0.90210544 0.86978451 0.50250109]
max value is :  0.9021054437194442
[0.45190414 0.08437286 0.5112379  0.71570032 0.66687816 0.73578877
 0.76348427 0.         0.86978451 0.50250109]


# 9. How to print all the values of an array?

In [70]:

z1= np.ones((4,4))
print(z1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [81]:
X=np.array([[3,5,7],[9,8,5],[12,11,10]])
x0=X[0,:].mean()
print("mean of first row: ",x0)
x1=X[1,:].mean()
print("mean of Second row: ",x1)
x2=X[2,:].mean()
print("mean of Third row: ",x2)
x4=X-X.mean(axis=1,keepdims=True)
print(x4)


mean of first row:  5.0
mean of Second row:  7.333333333333333
mean of Third row:  11.0
[[-2.          0.          2.        ]
 [ 1.66666667  0.66666667 -2.33333333]
 [ 1.          0.         -1.        ]]


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector

In [100]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[9 8 0 2 6 6 4 0 1 2 2 5 1 6 4 4 2 9 0 9]
[4. 3. 5. 1. 4. 2. 4. 1. 2. 4.]


# 12.How to get the diagonal of a dot product?

In [104]:
l= np.random.randint(0,9,(3,3))
print("L = ",l)
m= np.random.randint(0,9,(3,3))
print("M = ",m)
n=np.diag(np.dot(l,m))
print("N = ",n)


L =  [[2 1 1]
 [1 7 2]
 [5 0 5]]
M =  [[6 6 8]
 [7 6 1]
 [8 5 4]]
N =  [27 58 60]


# 13How to find the most frequent value in an array?

In [108]:
mm = np.random.randint(0,10,50)
print (mm)
print('rank:', np.bincount(mm).argmax())

[5 2 0 0 6 4 7 7 4 2 3 3 0 9 5 6 2 6 7 1 3 4 0 4 5 0 3 1 3 4 1 2 5 1 3 2 9
 2 0 0 9 7 9 2 5 2 9 6 9 6]
rank: 2


# 14.How to get the n largest values of an array

# 15.How to create a record array from a regular array?
